config {
  type: "view",
  assertions: {
    nonNull: ["event_date", "event_name"],
    rowConditions: ["usuarios_view_item > 0, usuarios_begin_checkout > 0, usuarios_purchase > 0, conversion_rate > 0"]
  },
  dependOnDependencyAssertions: true,
  description: "Tabela gold trazendo informacoes de quantidade de views_item, begin_checkout, purchase e taxa de conversao",
  columns: {
    event_date: { description: "Data do evento" },
    usuarios_view_item: { description: "Quantidade de usuarios distintos que realizaram um evento de view_item" },
    usuarios_begin_checkout: { description: "Quantidade de usuarios distintos que realizaram um evento de begin_checkout" },
    usuarios_purchase: { description: "Quantidade de usuarios distintos que realizaram um evento de purchase" },
    conversion_rate: { description: "Taxa de conversao de compra qtd_begin_checkout / qtd_purchase" }
  }
}

WITH silver_events AS (

SELECT
  event_date
  user_pseudo_id,
  event_name
FROM ${ref("silver_events")}

),

count_events AS (

SELECT
  event_date,
  COUNT(DISTINCT IF(event_name = 'view_item', user_pseudo_id, NULL)) AS usuarios_view_item,
  COUNT(DISTINCT IF(event_name = 'begin_checkout', user_pseudo_id, NULL)) AS usuarios_begin_checkout,
  COUNT(DISTINCT IF(event_name = 'purchase', user_pseudo_id, NULL)) AS usuarios_purchase
FROM silver_events

)

SELECT
  event_date,
  usuarios_view_item,
  usuarios_begin_checkout,
  usuarios_purchase,
  SAFE_DIVIDE(usuarios_purchase, usuarios_begin_checkout) AS conversion_rate
FROM count_events